project 'App/App.xcodeproj'

platform :ios, '12.1'

target 'App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for App
  def shared_pods
    pod 'MaterialComponents/schemes/Typography'
    pod 'MaterialComponents/schemes/Color'
    pod 'SwiftLint'
    pod 'Kingfisher'
  end

  target 'AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppUITests' do
    inherit! :complete
    # Pods for testing
    shared_pods
    pod 'Embassy', '~> 4.1'
    pod 'EnvoyAmbassador', '~> 4.0'
  end

end
