# Uncomment the next line to define a global platform for your project
 platform :ios, '10.3'

inhibit_all_warnings!

def shared_pods
  ## Linter and Formatter
      pod 'SwiftLint'
      
end
  
target 'uitests (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uitests (iOS)
  

end

target 'uitests (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for uitests (macOS)

end

target 'Tests iOS' do
    
    use_frameworks!
    
    inherit! :search_paths
    # Pods for testing
    shared_pods
    pod 'Embassy', '~> 4.1'
    pod 'EnvoyAmbassador', '~> 4.0'
    
end
